# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingRef', models.CharField(max_length=100)),
                ('ticketNumber', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('dateOfBooking', models.DateTimeField(auto_now_add=True)),
                ('dateOfTravel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('approvalCode', models.CharField(max_length=200)),
                ('bookingRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
